api_login:
  path: /api/login

register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: POST

FileUploadController:
    path: /api/upload-file
    controller: App\Controller\FileUploadController::upload
    methods: POST

api_user_datetime_create:
    path: /api/user/{userId}/datetime
    controller: App\Controller\UserDateTimeController::create
    methods: POST

api_user_datetime_recent:
    path: /api/user/{userId}/datetime/recent
    controller: App\Controller\UserDateTimeController::getRecentUserDateTime
    methods: GET

api_user_datetime_edit:
    path: /api/user/{userId}/datetime/edit
    controller: App\Controller\AjusteColabController::getEditUserDateTime
    methods: GET

api_user_datetime_modify:
    path: /api/user/{userId}/datetime/modify
    controller: App\Controller\AjusteColabController::modify
    methods: POST

api_user_datetime_modify_update:
    path: /api/user/{userId}/datetime/modify/update
    controller: App\Controller\AjusteColabController::update
    methods: PUT

user_approve_time:
    path: /api/user/approve/time
    controller: App\Controller\AprovarController::getTimeApprove
    methods: GET

user_approve_patch:
    path: /api/user/approve/patch
    controller: App\Controller\AprovarController::patchUserDateTime
    methods: PATCH

api_user_approve_delete_insert:
    path: /api/user/approve/delete/insert
    controller: App\Controller\AprovarController::deleteInsertNoApprove
    methods: POST

api_user_file:
    path: /api/user/{userId}/file
    controller: App\Controller\FileSearchController::getfile
    methods: GET

api_user_profile:
    path: /api/user/{userId}/profile
    controller: App\Controller\ProfileController::getProfile
    methods: GET

api_user_all_profile:
    path: /api/user/profile
    controller: App\Controller\ProfileController::getAllProfile
    methods: GET

api_user_userid_profile/edit:
    path: /api/user/{userId}/profile/edit
    controller: App\Controller\ProfileController::salveUpdateUser
    methods: POST

api_user_user_painel_buscahoras:
    path: /api/user/painel/buscahoras
    controller: App\Controller\PainelCalculoController::buscaHoras
    methods: GET

api_user_user_painel_buscahorasCalculadas:
    path: /api/user/painel/buscahorasCalculadas
    controller: App\Controller\PainelCalculoController::buscaHorasCalculadas
    methods: GET

api_user_feriado_salvar:
    path: /api/user/feriado/salvarFeriados
    controller: App\Controller\FeriadoController::salvarFeriados
    methods: POST

api_user_feriado_buscar:
    path: /api/user/feriado/getFeriado
    controller: App\Controller\FeriadoController::buscarFeriados
    methods: GET