api_login:
  path: /api/login

register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: POST

FileUploadController:
    path: /api/upload-file
    controller: App\Controller\FileUploadController::upload
    methods: POST

api_user_datetime_create:
    path: /api/user/{userId}/datetime
    controller: App\Controller\UserDateTimeController::create
    methods: POST

api_user_datetime_recent:
    path: /api/user/{userId}/datetime/recent
    controller: App\Controller\UserDateTimeController::getRecentUserDateTime
    methods: GET

api_user_datetime_edit:
    path: /api/user/{userId}/datetime/edit
    controller: App\Controller\UserDateTimeController::getEditUserDateTime
    methods: GET